const SHOP_DATA = 
[
  {
    title: 'products',
    items: 
    [
      {
        title: 'products',
        items: [
          {
            id: 1,
            name: 'Hollywood Drive Hat',
            imageUrl: 'https://i.imgur.com/qSdk8Dr.png',
            price: 160,
            categories: ['hat','men'],
          },
          {
            id: 2,
            name: 'Stetson Roxbury Hat',
            imageUrl: 'https://i.imgur.com/MPzljbf.png',
            price: 120,
            categories: ['hat','men'],
          },
          {
            id: 3,
            name: 'Santa Fe Hat',
            imageUrl: 'https://i.imgur.com/uc9REWY.png',
            price: 150,
            categories: ['hat','men'],
          },
          {
            id: 4,
            name: 'Santa Clara Felt Cowboy Hat',
            imageUrl: 'https://i.imgur.com/cZQCvnl.png',
            price: 280,
            categories: ['hat','men'],
          },
          {
            id: 5,
            name: 'Smoke Grey Concho Buckle Band Wool Felt Western Hat',
            imageUrl: 'https://i.imgur.com/xaWqcUQ.png',
            price: 80,
            categories: ['hat','men'],
          },
          {
            id: 6,
            name: 'Cattleman\'s Crease Straw Western Hat',
            imageUrl: 'https://i.imgur.com/5VDTPct.png',
            price: 40,
            categories: ['hat','men'],
          },
          {
            id: 7,
            name: 'Silver Belly Pinch Front Straw Western Hat',
            imageUrl: 'https://i.imgur.com/TeTRU3a.png',
            price: 150,
            categories: ['hat','women'],
          },
          {
            id: 8,
            name: 'Grey Denim Trompo Cloth Ribbon Wool Felt Western Hat',
            imageUrl: 'https://i.imgur.com/1eU2S3C.png',
            price: 300,
            categories: ['hat','women'],
          },
          {
            id: 9,
            name: 'Dallas Beaver Fur Felt Western Hat',
            imageUrl: 'https://i.imgur.com/4vjKlxA.png',
            price: 270,
            categories: ['hat','women'],
          },
          {
            id: 10,
            name: 'Big Splash Splattered Print Western Straw Hat',
            imageUrl: 'https://i.imgur.com/yfJjIZV.png',
            price: 60,
            categories: ['hat','women'],
          },
          {
            id: 11,
            name: 'Copper Duck Canvas Button-front Trucker Rust Jacket',
            imageUrl: 'https://i.imgur.com/N9dpvw3.png',
            price: 70,
            categories: ['outerwear','men'],
          },
          {
            id: 12,
            name: 'All In 1/4 Snap Geo Print Fleece Pullover',
            imageUrl: 'https://i.imgur.com/aVZAXwa.png',
            price: 70,
            categories: ['outerwear','men'],
          },
          {
            id: 13,
            name: 'Jarvis Southwestern Wool Shacket',
            imageUrl: 'https://i.imgur.com/gY5bG52.png',
            price: 120,
            categories: ['outerwear','men'],
          },
          {
            id: 14,
            name: 'Edward Faux Suede Sherpa Collar Bomber Jacket',
            imageUrl: 'https://i.imgur.com/fgyUooL.png',
            price: 80,
            categories: ['outerwear','men'],
          },
          {
            id: 15,
            name: 'Oak Hill Corduroy Color Block Jacket',
            imageUrl: 'https://i.imgur.com/jKg2WMh.png',
            price: 90,
            categories: ['outerwear','women'],
          },
          {
            id: 16,
            name: 'Embroidered Suede Fringe Jacket',
            imageUrl: 'https://i.imgur.com/OXtZcgl.png',
            price: 400,
            categories: ['outerwear','women'],
          },
          {
            id: 17,
            name: 'Studded Fringe Suede Jacket',
            imageUrl: 'https://i.imgur.com/opafKFq.png',
            price: 325,
            categories: ['outerwear','women'],
          },
          {
            id: 18,
            name: 'Stable Southwestern Print Sherpa Jacket',
            imageUrl: 'https://i.imgur.com/PJzvGJ3.png',
            price: 230,
            categories: ['outerwear','women'],
          },
          {
            id: 19,
            name: 'Medium Wash Sherpa-lined Denim Jacket',
            imageUrl: 'https://i.imgur.com/v1vbAyp.png',
            price: 100,
            categories: ['outerwear','women'],
          },
          {
            id: 20,
            name: 'Drop Waist Button Front Sleeveless Midi Dress',
            imageUrl: 'https://i.imgur.com/8dz7kWB.png',
            price: 70,
            categories: ['dress','women'],
          },
          {
            id: 21,
            name: 'Strawberry Hill Embroidered Floral Fringe Dress',
            imageUrl: 'https://i.imgur.com/NPZera4.png',
            price: 70,
            categories: ['dress','women'],
          },
          {
            id: 22,
            name: 'Lace-up Jacquard Dress',
            imageUrl: 'https://i.imgur.com/gtsw0QA.png',
            price: 90,
            categories: ['dress','women'],
          },
          {
            id: 23,
            name: 'Sheer Floral Print Tank Dress',
            imageUrl: 'https://i.imgur.com/SRgTPzg.png',
            price: 110,
            categories: ['dress','women'],
          },
          {
            id: 24,
            name: 'Cora Color Block Shirt Dress',
            imageUrl: 'https://i.imgur.com/D51QIik.png',
            price: 140,
            categories: ['dress','women'],
          },
          {
            id: 25,
            name: 'Denim Long Sleeve Western Dress',
            imageUrl: 'https://i.imgur.com/D52Xwgf.png',
            price: 110,
            categories: ['dress','women'],
          },
          {
            id: 26,
            name: 'Full-quill Ostrich Exotic Western Boots',
            imageUrl: 'https://i.imgur.com/GZxOJ6H.png',
            price: 450,
            categories: ['boot','men'],
          },
          {
            id: 27,
            name: 'Exotic Ostrich Leg Western Boots',
            imageUrl: 'https://i.imgur.com/sDQEqzf.png',
            price: 339,
            categories: ['boot','men'],
          },
          {
            id: 28,
            name: 'Blaire Western Boots',
            imageUrl: 'https://i.imgur.com/RlHcVsH.png',
            price: 200,
            categories: ['boot','women'],
          },
          {
            id: 29,
            name: 'Calypso Leather Western Bridal Boots',
            imageUrl: 'https://i.imgur.com/EPjT43Z.png',
            price: 350,
            categories: ['boot','women'],
          },
          {
            id: 30,
            name: 'Western Cowboy Embroidered Long Sleeve Button Down Shirt',
            imageUrl: 'https://i.imgur.com/S5OXbYf.png',
            price: 30,
            categories: ['top','men'],
          },
          {
            id: 31,
            name: 'Diamond Striped Short Sleeve Snap Western Shirt',
            imageUrl: 'https://i.imgur.com/Aa3NrgB.png',
            price: 50,
            categories: ['top','men'],
          },
          {
            id: 32,
            name: 'Casual Plaid Print Long Sleeve Woven Shirt',
            imageUrl: 'https://i.imgur.com/0nlkpeR.png',
            price: 45,
            categories: ['top','men'],
          },
          {
            id: 33,
            name: 'Instinct Long Sleeve Western Snap Shirt',
            imageUrl: 'https://i.imgur.com/elB2S3E.png',
            price: 65,
            categories: ['top','men'],
          },
          {
            id: 34,
            name: 'Lost Trail Plaid Print Long Sleeve Snap Western Shirt',
            imageUrl: 'https://i.imgur.com/7oPDjqe.png',
            price: 40,
            categories: ['top','men'],
          },
          {
            id: 35,
            name: 'Vintage Border Long Sleeve Western Snap Shirt',
            imageUrl: 'https://i.imgur.com/RJiXWuf.png',
            price: 70,
            categories: ['top','men'],
          },
          {
            id: 36,
            name: 'Floral Embroidered Prue Blouse',
            imageUrl: 'https://i.imgur.com/n7S8r63.png',
            price: 300,
            categories: ['top','women'],
          },
          {
            id: 37,
            name: 'Powell Sequin Fringe Cami',
            imageUrl: 'https://i.imgur.com/g1Y0QVM.png',
            price: 60,
            categories: ['top','women'],
          },
          {
            id: 38,
            name: 'Embellished Velvet Long Sleeve Button Down Western Shirt',
            imageUrl: 'https://i.imgur.com/lUYQqhc.png',
            price: 130,
            categories: ['top','women'],
          },
          {
            id: 39,
            name: 'Plaid Print Chest Pocket Long Sleeve Shirt',
            imageUrl: 'https://i.imgur.com/1JYtGGj.png',
            price: 50,
            categories: ['top','women'],
          },
          {
            id: 40,
            name: 'Kirby Striped Long Sleeve Button Down Stretch Shirt',
            imageUrl: 'https://i.imgur.com/gzOTfiB.png',
            price: 55,
            categories: ['top','women'],
          },
          {
            id: 41,
            name: 'Pistol Medium Vintage Wash Straight Jeans',
            imageUrl: 'https://i.imgur.com/8mAUbXF.png',
            price: 90,
            categories: ['bottom','men'],
          },
          {
            id: 42,
            name: 'Dark Wash Pistol Stackable Reflex Bootcut Jeans',
            imageUrl: 'https://i.imgur.com/Y2RHCq2.png',
            price: 90,
            categories: ['bottom','men'],
          },
          {
            id: 43,
            name: 'Dark Rinse Relaxed Boot Performance Stretch Denim Jeans',
            imageUrl: 'https://i.imgur.com/UqdkGED.png',
            price: 75,
            categories: ['bottom','men'],
          },
          {
            id: 44,
            name: 'Crupper Light Wash Stretch Slim Straight Jeans',
            imageUrl: 'https://i.imgur.com/LHJCTwC.png',
            price: 55,
            categories: ['bottom','men'],
          },
          {
            id: 45,
            name: 'Tan Wash Dalton Stretch Slim Straight Jeans',
            imageUrl: 'https://i.imgur.com/xrEwJI2.png',
            price: 55,
            categories: ['bottom','men'],
          },
          {
            id: 46,
            name: 'Dark Wash High Rise Slim Stretch Straight Jeans',
            imageUrl: 'https://i.imgur.com/4CjhaKk.png',
            price: 75,
            categories: ['bottom','women'],
          },
          {
            id: 47,
            name: 'Distressed High Rise Straight Jeans',
            imageUrl: 'https://i.imgur.com/iSh9Tpv.png',
            price: 75,
            categories: ['bottom','women'],
          },
          {
            id: 48,
            name: 'Rhinestone Studded Lace-up Flare Leather Pants',
            imageUrl: 'https://i.imgur.com/LMYxcBx.png',
            price: 450,
            categories: ['bottom','women'],
          },
          {
            id: 49,
            name: 'Star Sequin Flare Pants',
            imageUrl: 'https://i.imgur.com/YVXhjuP.png',
            price: 380,
            categories: ['bottom','women'],
          },
          {
            id: 50,
            name: 'Fringe Flapper Mini Skirt',
            imageUrl: 'https://i.imgur.com/SCdCgev.png',
            price: 65,
            categories: ['bottom','women'],
          },
          {
            id: 51,
            name: 'Rhinestone Studded Fringe Denim Mini Skirt',
            imageUrl: 'https://i.imgur.com/SLjUB9R.png',
            price: 60,
            categories: ['bottom','women'],
          },
          {
            id: 52,
            name: 'Floral Tooled Leather Belt',
            imageUrl: 'https://i.imgur.com/KleAYUF.png',
            price: 60,
            categories: ['accessory','men'],
          },
          {
            id: 53,
            name: 'Classic Western Belt',
            imageUrl: 'https://i.imgur.com/FQaFqAu.png',
            price: 60,
            categories: ['accessory','men'],
          },
          {
            id: 54,
            name: 'Tooled Leather Belt',
            imageUrl: 'https://i.imgur.com/CqsLoDG.png',
            price: 75,
            categories: ['accessory','women'],
          },
          {
            id: 55,
            name: 'American Cowboy Flag Buckle With Eagle',
            imageUrl: 'https://i.imgur.com/8pOHMMN.png',
            price: 120,
            categories: ['accessory','men'],
          },
          {
            id: 56,
            name: '"bryce" Vintage Two-tone Steer Head With Barbwire Frame',
            imageUrl: 'https://i.imgur.com/Es56BCk.png',
            price: 160,
            categories: ['accessory'],
          },
          {
            id: 57,
            name: 'Tri-color Champion Texas Longhorn Buckle',
            imageUrl: 'https://i.imgur.com/SfPFzFR.png',
            price: 130,
            categories: ['accessory'],
          },
          {
            id: 58,
            name: 'Cowboy Boots Salt And Pepper Shaker',
            imageUrl: 'https://i.imgur.com/oxUuujt.png',
            price: 25,
            categories: ['accessory'],
          },
          {
            id: 59,
            name: 'Travis Bi-fold Wallet',
            imageUrl: 'https://i.imgur.com/P7uLJE8.png',
            price: 80,
            categories: ['accessory'],
          },
          {
            id: 60,
            name: 'Cattle Driven Bi-fold Wallet',
            imageUrl: 'https://i.imgur.com/SJCRkOx.png',
            price: 60,
            categories: ['accessory'],
          },
          {
            id: 61,
            name: 'Twin Pistols Wine Holder',
            imageUrl: 'https://i.imgur.com/qhWq71d.png',
            price: 50,
            categories: ['accessory'],
          },
          {
            id: 62,
            name: 'Highway Rose Biker Western Wine Bottle Stopper',
            imageUrl: 'https://i.imgur.com/E3P14Px.png',
            price: 20,
            categories: ['accessory'],
          },
          {
            id: 63,
            name: 'Cowboy Barber\'s Dream Western Wine Bottle Stopper',
            imageUrl: 'https://i.imgur.com/uVwHG0O.png',
            price: 20,
            categories: ['accessory'],
          },
          {
            id: 64,
            name: 'Scruffy Western Wine Bottle Stopper',
            imageUrl: 'https://i.imgur.com/e8NsOEz.png',
            price: 20,
            categories: ['accessory'],
          },
          {
            id: 65,
            name: 'Road Warrior Biker Western Wine Bottle Stopper',
            imageUrl: 'https://i.imgur.com/EFdERZb.png',
            price: 20,
            categories: ['accessory'],
          },
        ],
      }
    ]
  }
];

export default SHOP_DATA;